title: Fairmodels
description: Towards fairer language models
theme: just-the-docs

url: https://fairmodels.github.io

aux_links:
  "GitHub": https://github.com/fairmodels/fairmodels.github.io

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Set a path/url to a logo that will be displayed instead of the title
favicon_ico: "/assets/images/iceberg.ico"

callouts:
  note:
    color: purple
