title: Fairtrain
description: Towards fairer training data
theme: just-the-docs

url: https://fairtrain.github.io

aux_links:
  "GitHub": https://github.com/fairtrain/fairtrain.github.io

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Set a path/url to a logo that will be displayed instead of the title
favicon_ico: "/assets/images/iceberg.ico"

callouts:
  note:
    color: purple
